export enum QuestionnaireStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
}

export enum MessageStatus {
  SENT = 'SENT',
  DELIVERED = 'DELIVERED',
  READ = 'READ',
}

export enum NotificationType {
  SESSION_REMINDER = 'SESSION_REMINDER',
  PROGRESS_UPDATE = 'PROGRESS_UPDATE',
  MESSAGE_RECEIVED = 'MESSAGE_RECEIVED',
  BADGE_EARNED = 'BADGE_EARNED',
  PROGRAM_UPDATED = 'PROGRAM_UPDATED',
  REPORT_READY = 'REPORT_READY',
}
