-- ============================================================
-- Migration 008 — Seed : 13 séances THRIVE × 3 tranches d'âge
-- Vidéos placeholder (à remplacer par les vraies depuis l'admin)
-- ============================================================

WITH base(session_number, phase, title, subtitle, theme, life_skill, thrive_action, is_free, video_url) AS (
  VALUES
    (1,  'ANCRER',     'Qui je suis sur la glace',        'Diagnostic de départ et alliance',          'Identité',              'Connaissance de soi',        'EVAL',    true,
     'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4'),
    (2,  'ANCRER',     'Mes objectifs, mon plan',         'Fixer un objectif SMART qui dépend de moi', 'Objectifs',             'Fixation d''objectifs',      'A1',      false,
     'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4'),
    (3,  'DEVELOPPER', 'Confiance et courage',            'Progresser par le défi maîtrisé',           'Confiance',             'Confiance en soi',           'A3',      true,
     'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4'),
    (4,  'DEVELOPPER', 'Identifier mes émotions',         'Reconnaître l''émotion pendant l''action',  'Émotions',              'Régulation émotionnelle',    'A2',      true,
     'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4'),
    (5,  'DEVELOPPER', 'Agir sur mes émotions',           'Mes stratégies de recentrage',              'Émotions',              'Régulation émotionnelle',    'A2',      false,
     'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4'),
    (6,  'DEVELOPPER', 'Rester calme sous pression',      'Relaxation en situation réelle',            'Gestion du stress',     'Gestion du stress',          'A5',      false,
     'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4'),
    (7,  'DEVELOPPER', 'Mon bilan mi-parcours',           'Où j''en suis, où je vais',                 'Bilan',                 'Intégration / autonomie',    'EVAL',    false,
     'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4'),
    (8,  'DEVELOPPER', 'Demander de l''aide',             'M''appuyer sur les autres, une force',      'Connexion',             'Demande d''aide / soutien',  'A4',      false,
     'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4'),
    (9,  'DEVELOPPER', 'Mon focus word',                  'Concentration intentionnelle',              'Concentration',         'Attention sélective',        'A6',      false,
     'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4'),
    (10, 'DEVELOPPER', 'Voir avant de faire',             'Imagerie mentale et visualisation',         'Préparation mentale',   'Préparation mentale',        'A6',      false,
     'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4'),
    (11, 'INTEGRER',   'Ma boîte à outils',               'Mes 6 outils THRIVE, partout dans ma vie',  'Transfert',             'Transfert actif',            'INTEG',   false,
     'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4'),
    (12, 'INTEGRER',   'Leadership et impact',            'Guider les autres à mon tour',              'Leadership',            'Impact sur l''entourage',    'CONTRIB', false,
     'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4'),
    (13, 'INTEGRER',   'Mon bilan final',                 'Célébrer le chemin parcouru',               'Bilan',                 'Identité THRIVE',            'EVAL',    false,
     'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4')
),
ages(age_group, age_desc) AS (
  VALUES
    ('8-11'::age_group,  'Version ludique et concrète, adaptée à la phase d''échantillonnage (8–11 ans) : jeu, variété et plaisir avant tout.'),
    ('12-14'::age_group, 'Version adaptée à la phase de spécialisation (12–14 ans) : engagement, début de pratique délibérée et premiers défis personnels.'),
    ('15-17'::age_group, 'Version adaptée à la phase d''investissement (15–17 ans) : pratique délibérée, orientation performance et identité d''athlète.')
)
INSERT INTO public.video_sessions
  (session_number, phase, title, subtitle, description, age_group, theme, life_skill,
   thrive_action, duration_minutes, video_url, lang, is_free, is_active, sort_order)
SELECT
  b.session_number,
  b.phase,
  b.title,
  b.subtitle,
  'Séance ' || b.session_number || ' — ' || b.subtitle || '. ' || a.age_desc ||
  ' À vivre ensemble, parent et enfant, pendant 20 minutes d''exercices interactifs guidés par le coach.',
  a.age_group,
  b.theme,
  b.life_skill,
  b.thrive_action,
  20,
  b.video_url,
  'fr',
  b.is_free,
  true,
  b.session_number
FROM base b
CROSS JOIN ages a
ON CONFLICT (session_number, age_group, lang) DO NOTHING;

-- ------------------------------------------------------------
-- Points d'interaction : 2 questions par séance (placeholder,
-- timecodes courts pour la démo — à recaler sur les vraies vidéos)
-- ------------------------------------------------------------
WITH q(session_number, ord, timecode, question, answers) AS (
  VALUES
    (1, 1, 12, 'Sur la glace, qu''est-ce qui te ressemble le plus ?',
     '[{"key":"A","label":"J''aime essayer plein de choses nouvelles","tag":"curiosite","score":2},
       {"key":"B","label":"J''aime quand je réussis un défi","tag":"confiance","score":2},
       {"key":"C","label":"J''aime jouer avec les autres","tag":"connexion","score":2},
       {"key":"D","label":"J''aime aller vite et me dépasser","tag":"energie","score":2}]'::jsonb),
    (1, 2, 38, 'Quel est ton rêve pour cette saison ?',
     '[{"key":"A","label":"Devenir plus fort techniquement","tag":"competence","score":2},
       {"key":"B","label":"Avoir plus confiance en moi","tag":"confiance","score":2},
       {"key":"C","label":"M''amuser à fond","tag":"plaisir","score":2},
       {"key":"D","label":"Faire partie d''une équipe","tag":"connexion","score":2}]'::jsonb),
    (2, 1, 12, 'Un bon objectif, c''est un objectif qui…',
     '[{"key":"A","label":"Dépend uniquement de moi","tag":"processus","score":3},
       {"key":"B","label":"Dépend du résultat du match","tag":"resultat","score":0},
       {"key":"C","label":"Est impossible à rater","tag":"facilite","score":1},
       {"key":"D","label":"Fait plaisir à mes parents","tag":"externe","score":0}]'::jsonb),
    (2, 2, 38, 'Choisis ton objectif de la semaine :',
     '[{"key":"A","label":"M''entraîner 10 minutes par jour","tag":"processus","score":3},
       {"key":"B","label":"Marquer 3 buts","tag":"resultat","score":1},
       {"key":"C","label":"Essayer un nouveau geste 5 fois","tag":"processus","score":3},
       {"key":"D","label":"Être le meilleur du groupe","tag":"comparaison","score":0}]'::jsonb),
    (3, 1, 12, 'Avant un défi difficile, qu''est-ce que tu te dis ?',
     '[{"key":"A","label":"Je vais essayer, étape par étape","tag":"confiance","score":3},
       {"key":"B","label":"Je n''y arriverai jamais","tag":"doute","score":0},
       {"key":"C","label":"Je le fais seulement si je suis sûr de réussir","tag":"evitement","score":1},
       {"key":"D","label":"J''y vais sans réfléchir","tag":"impulsivite","score":1}]'::jsonb),
    (3, 2, 38, 'Tu viens de rater ton essai. Que fais-tu ?',
     '[{"key":"A","label":"Je réessaie en changeant un petit détail","tag":"perseverance","score":3},
       {"key":"B","label":"J''abandonne ce défi","tag":"abandon","score":0},
       {"key":"C","label":"Je demande un conseil","tag":"aide","score":3},
       {"key":"D","label":"Je me fâche contre moi-même","tag":"dureté","score":0}]'::jsonb),
    (4, 1, 12, 'Ton cœur bat fort avant un exercice. C''est plutôt…',
     '[{"key":"A","label":"De l''excitation — j''ai hâte !","tag":"emotion_positive","score":2},
       {"key":"B","label":"Du stress — j''ai peur de rater","tag":"stress","score":2},
       {"key":"C","label":"De la colère","tag":"colere","score":2},
       {"key":"D","label":"Je ne sais pas trop","tag":"exploration","score":1}]'::jsonb),
    (4, 2, 38, 'Où sens-tu l''émotion dans ton corps ?',
     '[{"key":"A","label":"Dans le ventre","tag":"interoception","score":2},
       {"key":"B","label":"Dans les épaules","tag":"interoception","score":2},
       {"key":"C","label":"Dans la tête","tag":"interoception","score":2},
       {"key":"D","label":"Partout en même temps","tag":"interoception","score":2}]'::jsonb),
    (5, 1, 12, 'Quand l''émotion devient trop forte, quel est TON outil ?',
     '[{"key":"A","label":"Respirer profondément 3 fois","tag":"respiration","score":3},
       {"key":"B","label":"Serrer les poings puis relâcher","tag":"relachement","score":3},
       {"key":"C","label":"Me répéter mon mot-clé","tag":"focus_word","score":3},
       {"key":"D","label":"Continuer comme si de rien n''était","tag":"evitement","score":0}]'::jsonb),
    (5, 2, 38, 'Après le recentrage, comment te sens-tu ?',
     '[{"key":"A","label":"Plus calme","tag":"regulation","score":3},
       {"key":"B","label":"Pareil qu''avant","tag":"neutre","score":1},
       {"key":"C","label":"Encore agité","tag":"activation","score":1},
       {"key":"D","label":"Fatigué","tag":"fatigue","score":1}]'::jsonb),
    (6, 1, 12, 'La pression monte. Quelle est la première chose à faire ?',
     '[{"key":"A","label":"Ralentir ma respiration","tag":"respiration","score":3},
       {"key":"B","label":"Aller plus vite pour en finir","tag":"precipitation","score":0},
       {"key":"C","label":"Penser à autre chose","tag":"distraction","score":1},
       {"key":"D","label":"Me concentrer sur mon prochain geste","tag":"focus","score":3}]'::jsonb),
    (6, 2, 38, 'C''est quoi, être calme sous pression ?',
     '[{"key":"A","label":"Ne plus rien ressentir","tag":"suppression","score":0},
       {"key":"B","label":"Ressentir la pression et rester concentré quand même","tag":"regulation","score":3},
       {"key":"C","label":"Éviter les situations stressantes","tag":"evitement","score":0},
       {"key":"D","label":"Faire semblant que tout va bien","tag":"masque","score":0}]'::jsonb),
    (7, 1, 12, 'Depuis le début du programme, qu''est-ce qui a le plus changé pour toi ?',
     '[{"key":"A","label":"Ma confiance","tag":"confiance","score":2},
       {"key":"B","label":"Ma gestion des émotions","tag":"emotions","score":2},
       {"key":"C","label":"Ma concentration","tag":"concentration","score":2},
       {"key":"D","label":"Mon plaisir de jouer","tag":"plaisir","score":2}]'::jsonb),
    (7, 2, 38, 'Pour la suite, tu veux surtout travailler…',
     '[{"key":"A","label":"Demander de l''aide plus facilement","tag":"aide","score":2},
       {"key":"B","label":"Rester concentré plus longtemps","tag":"concentration","score":2},
       {"key":"C","label":"Me préparer mentalement","tag":"preparation","score":2},
       {"key":"D","label":"Aider les autres à progresser","tag":"leadership","score":2}]'::jsonb),
    (8, 1, 12, 'Demander de l''aide, c''est…',
     '[{"key":"A","label":"Un signe de faiblesse","tag":"croyance_negative","score":0},
       {"key":"B","label":"Une force des grands athlètes","tag":"croyance_positive","score":3},
       {"key":"C","label":"Réservé aux débutants","tag":"croyance_negative","score":0},
       {"key":"D","label":"Utile seulement en cas d''urgence","tag":"croyance_mixte","score":1}]'::jsonb),
    (8, 2, 38, 'À qui peux-tu demander de l''aide cette semaine ?',
     '[{"key":"A","label":"Mon coach","tag":"reseau","score":2},
       {"key":"B","label":"Un parent","tag":"reseau","score":2},
       {"key":"C","label":"Un ami ou coéquipier","tag":"reseau","score":2},
       {"key":"D","label":"Un professeur","tag":"reseau","score":2}]'::jsonb),
    (9, 1, 12, 'Choisis ton focus word pour cet exercice :',
     '[{"key":"A","label":"« Calme »","tag":"focus_word","score":2},
       {"key":"B","label":"« Précis »","tag":"focus_word","score":2},
       {"key":"C","label":"« Fort »","tag":"focus_word","score":2},
       {"key":"D","label":"« Fluide »","tag":"focus_word","score":2}]'::jsonb),
    (9, 2, 38, 'Ton attention s''échappe. Que fais-tu ?',
     '[{"key":"A","label":"Je répète mon focus word et je reviens","tag":"refocus","score":3},
       {"key":"B","label":"Je me dispute intérieurement","tag":"dureté","score":0},
       {"key":"C","label":"J''arrête l''exercice","tag":"abandon","score":0},
       {"key":"D","label":"Je remarque la distraction, puis je reviens au geste","tag":"refocus","score":3}]'::jsonb),
    (10, 1, 12, 'Ferme les yeux et imagine ton geste parfait. Que vois-tu ?',
     '[{"key":"A","label":"Je me vois de l''extérieur, comme une vidéo","tag":"imagerie_externe","score":2},
       {"key":"B","label":"Je le vis de l''intérieur, comme pour de vrai","tag":"imagerie_interne","score":3},
       {"key":"C","label":"C''est flou pour l''instant","tag":"apprentissage","score":1},
       {"key":"D","label":"Je ressens surtout les sensations","tag":"kinesthesie","score":2}]'::jsonb),
    (10, 2, 38, 'Quand utiliser la visualisation ?',
     '[{"key":"A","label":"Juste avant un match ou un examen","tag":"transfert","score":3},
       {"key":"B","label":"Seulement à l''entraînement","tag":"contexte_limite","score":1},
       {"key":"C","label":"Le soir, pour préparer demain","tag":"transfert","score":3},
       {"key":"D","label":"Jamais, ça ne sert à rien","tag":"croyance_negative","score":0}]'::jsonb),
    (11, 1, 12, 'Quel outil THRIVE as-tu déjà utilisé EN DEHORS du sport ?',
     '[{"key":"A","label":"La respiration avant un examen","tag":"transfert","score":3},
       {"key":"B","label":"Un objectif SMART pour l''école","tag":"transfert","score":3},
       {"key":"C","label":"Mon focus word pour les devoirs","tag":"transfert","score":3},
       {"key":"D","label":"Demander de l''aide à un prof","tag":"transfert","score":3}]'::jsonb),
    (11, 2, 38, 'Complète : « Je suis quelqu''un qui… »',
     '[{"key":"A","label":"…a des outils pour avancer","tag":"identite","score":3},
       {"key":"B","label":"…a encore besoin qu''on l''aide tout le temps","tag":"dependance","score":1},
       {"key":"C","label":"…réussit seulement quand c''est facile","tag":"fragilite","score":0},
       {"key":"D","label":"…progresse à chaque défi","tag":"identite","score":3}]'::jsonb),
    (12, 1, 12, 'Être un leader, c''est d''abord…',
     '[{"key":"A","label":"Donner des ordres","tag":"autorite","score":0},
       {"key":"B","label":"Montrer l''exemple et encourager","tag":"leadership","score":3},
       {"key":"C","label":"Être le plus fort","tag":"domination","score":0},
       {"key":"D","label":"Aider quelqu''un à réussir","tag":"contribution","score":3}]'::jsonb),
    (12, 2, 38, 'À qui vas-tu apprendre un outil THRIVE cette semaine ?',
     '[{"key":"A","label":"À un parent","tag":"contribution","score":2},
       {"key":"B","label":"À un ami","tag":"contribution","score":2},
       {"key":"C","label":"À un coéquipier","tag":"contribution","score":2},
       {"key":"D","label":"À un petit frère ou une petite sœur","tag":"contribution","score":2}]'::jsonb),
    (13, 1, 12, 'De quoi es-tu le plus fier depuis la séance 1 ?',
     '[{"key":"A","label":"De mes progrès techniques","tag":"competence","score":2},
       {"key":"B","label":"De ma confiance","tag":"confiance","score":2},
       {"key":"C","label":"De mes outils mentaux","tag":"outils","score":2},
       {"key":"D","label":"Du temps passé avec ma famille","tag":"connexion","score":2}]'::jsonb),
    (13, 2, 38, 'Dans ta lettre à toi-même dans 1 an, tu écris surtout…',
     '[{"key":"A","label":"Ce que je veux continuer","tag":"continuite","score":2},
       {"key":"B","label":"Ce que je veux devenir","tag":"identite","score":2},
       {"key":"C","label":"Ce que j''ai appris","tag":"bilan","score":2},
       {"key":"D","label":"Un message d''encouragement","tag":"autocompassion","score":2}]'::jsonb)
)
INSERT INTO public.video_interaction_points (video_session_id, timecode_seconds, question_text, answers)
SELECT vs.id, q.timecode, q.question, q.answers
FROM public.video_sessions vs
JOIN q ON q.session_number = vs.session_number
WHERE vs.lang = 'fr'
  AND NOT EXISTS (
    SELECT 1 FROM public.video_interaction_points vip
    WHERE vip.video_session_id = vs.id
      AND vip.timecode_seconds = q.timecode
  );
